name: "Test"
on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Earthly
        uses: earthly/actions-setup@v1
        with:
          version: "latest"
      - name: Test
        run: earthly +test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}