name: "Test"
on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run hello action
        uses: ./actions/hello
        with:
          who-to-greet: "Mona the Octocat"