name: "Test"
on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run hello action
        uses: jmgilman/actions-playground/actions/hello@actions/hello/v1.0.0
        with:
          who-to-greet: "Mona the Octocat"